<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="HPPH.SkiaSharp" Version="1.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.11" />
    <PackageReference Include="StableDiffusion.NET" Version="7.0.0" />
    <PackageReference Include="StableDiffusion.NET.Backend.Vulkan" Version="7.0.0" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Models\stable-diffusion-v1-5-pruned-emaonly-Q4_0.gguf">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
